import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar";

import '@fortawesome/fontawesome-free/css/all.min.css';
import NextAuthProvider from "@/providers/components/nextauth.providers";
import Providers from "@/providers/components/ReactQueryProvider.Provider";
import { ToastContainer } from 'react-toastify';

const Encode = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight: ['300', '400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* تجاهل فروقات هيدرشن عامة لو فيه إضافات بتعبث بالـDOM */}
      <body className={`${Encode.className} antialiased`} suppressHydrationWarning>

        <Providers>
          <ToastContainer />
          {/* شلنا justify-between عشان ميفضلّش فيه فراغ بين الهيدر والصفحة */}
          <div className="flex flex-col min-h-screen">
            <NextAuthProvider>
              <Navbar />
              <div className="container pt-0 mt-0">{children}</div>
            </NextAuthProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
